### ISSUE TITLE
No debezium connector type for cassandra

### ISSUE THREAD

**Issue by nehamidha** [debezium/debezium-connector-cassandra#1]
I am trying to register a connector for cassandra using kafka-connect. As per the [documentation](https://debezium.io/documentation/reference/1.3/install.html)  I have given the plugin.path a value to the cassandra plugin archive folder download from the same source. I am getting this exception while launching the kafka-connector

java.util.concurrent.ExecutionException: org.apache.kafka.connect.runtime.rest.errors.BadRequestException: Connector config {http.port=8000, kafka.producer.retries=3, cassandra.hosts=127.0.0.1, cassandra.port=9042, latest.commit.log.only=true, offset.backing.store.dir=/Users/delhivery/Desktop/cassandra-connector/test_dir/, connector.name=test_connector, kafka.producer.retry.backoff.ms=1000, kafka.producer.bootstrap.servers=127.0.0.1:9092, kafka.topic.prefix=test_prefix, value.converter=org.apache.kafka.connect.json.JsonConverter, snapshot.consistency=ONE, commit.log.relocation.dir=/Users/delhivery/Desktop/cassandra-connector/relocation/, key.converter=org.apache.kafka.connect.storage.StringConverter, snapshot.mode=ALWAYS, cassandra.config=/usr/local/etc/cassandra/cassandra.yaml} contains no connector type
	at org.apache.kafka.connect.util.ConvertingFutureCallback.result(ConvertingFutureCallback.java:115)
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:99)
	at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:118)

connector.properties I used: 

```connector.name=test_connector
commit.log.relocation.dir=/Users/delhivery/Desktop/cassandra-connector/relocation/
http.port=8000

cassandra.config=/usr/local/etc/cassandra/cassandra.yaml
cassandra.hosts=127.0.0.1
cassandra.port=9042


kafka.producer.bootstrap.servers=127.0.0.1:9092
kafka.producer.retries=3
kafka.producer.retry.backoff.ms=1000
kafka.topic.prefix=test_prefix

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter

offset.backing.store.dir=/Users/delhivery/Desktop/cassandra-connector/test_dir/

snapshot.consistency=ONE
snapshot.mode=ALWAYS

latest.commit.log.only=true```

I checked examples for other databases. A property (connector.class) needs to be specified in the connector.properties But i could not find a value for this property. As there is no class extending SourceConnector in io.debezium.connector.cassandra package. 

Please help me fix this issue. Is there something i am missing or doing wrong

**Comment by ahmedjami** [comment]
Hi @nehamidha 
here is what is noted in the Cassandra Connector doc:
> Cassandra is different from the other Debezium connectors since it is not implemented on top of the Kafka Connect framework. Instead it is a single JVM process that is intended to reside on each Cassandra node and publishes events to Kafka via a Kafka producer.

**Comment by nehamidha** [comment]
Okay @ahmedjami 
I understood the mistake. I guess I need to explore more on how to launch the debezium connector for cassandra.
Thanks :)

**Comment by jpechane** [comment]
@nehamidha Hi, there is a PR in progress that shows how to deploy Cassandra connector - https://github.com/debezium/debezium-examples/pull/139

The PR is almost finished so you can take a look.
